# Generated by Django 3.1.7 on 2021-04-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='Product_images')),
                ('Description', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('Author', models.CharField(blank=True, max_length=50)),
                ('Price1', models.FloatField(default=0)),
                ('Price2', models.FloatField(default=0)),
                ('Price3', models.FloatField(default=0)),
                ('Price4', models.FloatField(default=0)),
                ('Publisher', models.CharField(blank=True, max_length=50)),
                ('Status', models.CharField(choices=[('Avl', 'Available'), ('Rnt', 'Rented'), ('Dmg', 'Damaged')], default='Avl', max_length=3)),
                ('CreatedAt', models.DateField(auto_now_add=True, null=True)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNo', models.CharField(max_length=13, unique=True)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DoorNo', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('LandMark', models.CharField(max_length=100)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgeRange', models.CharField(help_text='Enter the age_range', max_length=20)),
                ('Image', models.ImageField(upload_to='Range_images')),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('Days', models.CharField(choices=[(1, '7 days'), (2, '14 days'), (3, '21 days'), (4, '28 days')], max_length=2)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emped_booksite.book')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emped_booksite.customer')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Age',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='Emped_booksite.range'),
        ),
        migrations.AddField(
            model_name='book',
            name='Genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='Emped_booksite.Category'),
        ),
    ]
