# Generated by Django 3.1.7 on 2021-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0002_auto_20210410_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgeRange', models.CharField(help_text='Enter the age_range', max_length=20)),
                ('Image', models.ImageField(upload_to='Range_images')),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
