# Generated by Django 3.1.7 on 2021-04-10 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0003_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Age',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='Emped_booksite.range'),
        ),
    ]
