# Generated by Django 3.1.7 on 2021-04-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0004_book_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(null=True, upload_to='Genres_images'),
        ),
    ]
