# Generated by Django 3.1.7 on 2021-04-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0005_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='Author_images')),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
