# Generated by Django 3.1.7 on 2021-04-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0007_auto_20210411_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
