# Generated by Django 3.2 on 2021-05-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0009_auto_20210510_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Damaged', 'Damaged')], default='Available', max_length=9),
        ),
    ]
