# Generated by Django 3.2.3 on 2021-05-21 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0010_alter_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='DoorNo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='LandMark',
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoorNo', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('LandMark', models.CharField(max_length=100)),
                ('IsDefault', models.BooleanField(default=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emped_booksite.customer')),
            ],
        ),
    ]
