# Generated by Django 3.2.3 on 2021-05-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0011_auto_20210520_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='IsDefault',
            field=models.BooleanField(default=False),
        ),
    ]
