# Generated by Django 3.2.3 on 2021-05-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0012_alter_customeraddress_isdefault'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
