# Generated by Django 3.2.3 on 2021-05-24 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0013_delete_customeraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoorNo', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('PinCode', models.CharField(max_length=6)),
                ('LandMark', models.CharField(max_length=100)),
                ('IsDefault', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emped_booksite.customer')),
            ],
        ),
    ]
