# Generated by Django 3.2.3 on 2021-05-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0014_customeraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
