# Generated by Django 3.2.3 on 2021-05-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0015_delete_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('Days', models.CharField(choices=[(1, '7 days'), (2, '14 days'), (3, '21 days'), (4, '28 days')], max_length=2)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emped_booksite.book')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emped_booksite.customer')),
            ],
        ),
    ]
