# Generated by Django 3.2.3 on 2021-05-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emped_booksite', '0020_rent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
